### ISSUE TITLE
KeepAlive is not working

### ISSUE THREAD

**Issue by ginkoob** [hashicorp/yamux#12]
Even if Config -> EnableKeepAlive and Config -> KeepAliveInterval are set and the connectivity is lost (i.e. internet goes down), `Session.Accept()` returns no error.
   I'm wondering if it's by design or if it is a bug. If Session.Accept doesn't return any error you can't implement fallback mechanism (e.g. redial the connection), isn't it?

**Comment by armon** [comment]
Hmm this is odd, the TCP connection itself should break if that is the case. The keep alive is mostly for NAT and load balancer traversal.

**Comment by rnapier** [comment]
I'm seeing similar problems. If I connect to a yamux server and then suspend either process (so it won't respond to pings), I expected that after the timeout (or some multiple) it would close the session.

TCP sessions can take a very, very long time (half an hour, multiples hours, or even days) to break on their own if the connection just goes away without a proper handshake. That's why you often need an app-layer heartbeat.

**Comment by ginkoob** [comment]
@armon  I think a Ping frame should serve both as a keepalive and as a means to  verify that the remote endpoint is still responsive.

**Comment by slackpad** [comment]
Hi @rnapier and @ginkoob  - totally agree - right now the ping process can get stuck waiting for a reply - I'll whip up a patch that adds a timeout and fails the connection.

**Comment by slackpad** [comment]
Sure - this should do it:

```go
package main

import (
        "fmt"
        "net"
)

func main() {
        ifcs, err := net.Interfaces()
        if err != nil {
                panic(err)
        }

        for _, ifc := range ifcs {
                fmt.Println(ifc.Name)
        }
}
```

You can save that as interface.go and then run `go build interface.go`, which should dump out the executable in the same directory.
